2025-06-17 10:20:06 [INFO] setup.py:52 - Logging system initialized
2025-06-17 10:20:06 [INFO] setup.py:53 - Log file: c:\Users\GILIEV\Documents\GitHub\Python-Projects\Chart generator\App\source\logs\chart_generator_20250617_102006.log
2025-06-17 10:20:06 [INFO] main_window.py:29 - Main window UI components initialized
2025-06-17 10:20:06 [INFO] app_controller.py:132 - Application initialized with modular components
2025-06-17 10:45:31 [ERROR] exception_handler.py:23 - Uncaught exception
Traceback (most recent call last):
  File "c:\Users\GILIEV\Documents\GitHub\Python-Projects\Chart generator\App\source\ChartGenerator_new_modular.py", line 41, in <module>
    root.destroy()
    ~~~~~~~~~~~~^^
  File "C:\Users\GILIEV\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2503, in destroy
    self.tk.call('destroy', self._w)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
